### ISSUE TITLE
Server need to wait all clients finished then stop

### ISSUE THREAD

**Issue by hansen7** [HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework#14]

**Comment by Roserland** [comment]
In some way it's needed. You can change the 'min_clients'(set the **_min_client_** equal to client_num) to control this process.

**Comment by Roserland** [comment]
In a single FL round, you can change the  _**if statement**_  in the first while loop to control this process.
In the whole FL process, Server will run several  iterations(set in `./server/config/config.json`) then stop.
