### ISSUE TITLE
Installation on apex

### ISSUE THREAD

**Issue by hansen7** [HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework#2]

**Comment by hansen7** [comment]
`apex`是必须的吗? 我试了一下pip安装不成功，是不是应该用这里提供的方式来装？
https://github.com/NVIDIA/apex#quick-start

**Comment by jiefenggan** [comment]
> `apex`是必须的吗? 我试了一下pip安装不成功，是不是应该用这里提供的方式来装？
> https://github.com/NVIDIA/apex#quick-start

apex是实现网络模型的混合精度训练（根据黑白名单自动决定使用FP16（GEMM, 卷积）还是FP32（Softmax）进行计算），用于提高训练速度。可以按照https://github.com/NVIDIA/apex#quick-start的方法安装

**Comment by hansen7** [comment]
> > `apex`是必须的吗? 我试了一下pip安装不成功，是不是应该用这里提供的方式来装？
> > https://github.com/NVIDIA/apex#quick-start
> 
> apex是实现网络模型的混合精度训练（根据黑白名单自动决定使用FP16（GEMM, 卷积）还是FP32（Softmax）进行计算），用于提高训练速度。可以按照[https://github.com/NVIDIA/apex#quick-start的方法安装](https://github.com/NVIDIA/apex#quick-start%E7%9A%84%E6%96%B9%E6%B3%95%E5%AE%89%E8%A3%85)

Okay, 那可能requirements.txt那里也得改改，`pip install -r requirements.txt`不work
