### ISSUE TITLE
Weights Aggregation

### ISSUE THREAD

**Issue by hansen7** [HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework#4]

**Comment by hansen7** [comment]
use `origin` variable or not?
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/aggregation.py#L41

https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/aggregation.py#L108-L110

**Comment by jiefenggan** [comment]
> use `origin` variable or not?
> https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/aggregation.py#L41
> 
> https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/aggregation.py#L108-L110

Don't use origin variable, we will update the code soon.

**Comment by hansen7** [comment]
Okay, thanks I am changing it now and will submit a pull request today
