### ISSUE TITLE
Matrix_op Build

### ISSUE THREAD

**Issue by hansen7** [HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework#5]
Does it require to build the `matrix_op`?

https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/LWE_based_PHE/matrix_op/matrix_op.py#L2

Or I think you are using an alternative solution as here:
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/LWE_based_PHE/cuda_test.py#L7-L12

**Comment by jiefenggan** [comment]
> Does it require to build the `matrix_op`?
> 
> https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/LWE_based_PHE/matrix_op/matrix_op.py#L2
> 
> Or I think you are using an alternative solution as here:
> https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/server/LWE_based_PHE/cuda_test.py#L7-L12

It require to build matrix_op, two methods(matmul, vecmul) have been redefined in this folder.

**Comment by hansen7** [comment]
Oh I see, but I didn't find a cmake or setup.py

**Comment by jiefenggan** [comment]
> Oh I see, but I didn't find a cmake or setup.py

This is done by calling C++ code through Python, without the need for CMake or setup.py to be pre-installed

**Comment by hansen7** [comment]
Clear, so the proper to call this function/module is shown in the `cuda_test.py`, using `load()` from `torch.utils.cpp_extension`, right?

**Comment by jiefenggan** [comment]
> Clear, so the proper to call this function/module is shown in the `cuda_test.py`, using `load()` from `torch.utils.cpp_extension`, right?

yes
