### ISSUE TITLE
Difference Between Client1_main.py and Client2_main.py

### ISSUE THREAD

**Issue by hansen7** [HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework#6]
I noticed that A lot of places in `Client1_main.py` and `Client2_main.py` are implemented differently, i.e. the first 70 lines are pretty much similar(except register the client), while the remaining parts are quite different. So I am wondering should I modify `Client2_main.py` w.r.t. `Client1_main.py`, right?

Or they are designed to be with different settings.

**Comment by Roserland** [comment]
There's is no significant difference between `Client1_main.py` and `Client2_main.py`, and the latter just removed somed unnecessary annotations. 

Pay attention to the CONFIG FILES,  like: `./config/client1_config.json` and `./config/train_config_client1.json`, they are different.

**Comment by hansen7** [comment]
了解，其实还是有些地方不太一样的。。。我列一下。。。

1. register or not:
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/42a10961e66c72511b35e843c9180be725868c30/client/client1_main.py#L20-L21
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/42a10961e66c72511b35e843c9180be725868c30/client/client2_main.py#L19-L21

2. and it seems that `client1_main.py` is set to be in an endless training, right?
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/42a10961e66c72511b35e843c9180be725868c30/client/client1_main.py#L101-L103
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/42a10961e66c72511b35e843c9180be725868c30/client/client1_main.py#L181-L183

3. which method for checkpoints fetching is preferred?
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/42a10961e66c72511b35e843c9180be725868c30/client/client1_main.py#L106-L118
https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/42a10961e66c72511b35e843c9180be725868c30/client/client2_main.py#L69-L70

Okay, 那我先改一下，然后交一版PR
