### ISSUE TITLE
`TrainDataset` Class defined in data_raw.py

### ISSUE THREAD

**Issue by hansen7** [HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework#7]

**Comment by hansen7** [comment]
Is this setting generable? Or I should calculate mine on my dataset?

https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/client/common/data_raw.py#L30-L36

**Comment by jiefenggan** [comment]
> Is this setting generable? Or I should calculate mine on my dataset?
> 
> https://github.com/HUST-EIC-AI-LAB/COVID-19-Fedrated-Learning-Framework/blob/d3714e76b3bc408fa79ed9e89372414701953b61/client/common/data_raw.py#L30-L36

We could use the same setting(mean and std) to train net. In our experiment, we could get an excellent enough model though Data from XieHe hospital is not this kind of data distribution.
But when you evaluate on your own data,  you should calculate yours on your dataset.

**Comment by Roserland** [comment]
May be not generable. This setting is calculated from the data we pre-used, and the data are usually different in some of their inherent properties.
You can use it at the pre-processing step,  but I don't recommend that using it at evaluations.
